language: python
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# whitelist
branches:
  only:
    - master
# install some archive programs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq archmage arj bzip2 lbzip2 pbzip2 cabextract ncompress cpio bsdcpio lzop lcab p7zip p7zip-full zip unzip rpm2cpio binutils arc nomarch unalz lrzip bsdtar rzip xdms lzip plzip clzip pdlzip sharutils flac unadf zpaq libchm-bin genisoimage rpm
# apt errors:
#E: Package 'p7zip-rar' has no installation candidate
#E: Package 'rar' has no installation candidate
#E: Package 'unrar' has no installation candidate
#E: Package 'lha' has no installation candidate
#E: Package 'orange' has no installation candidate
#E: Unable to locate package unace-nonfree
#E: Unable to locate package zopfli

# Note: pigz gives test errors on Travis CI since option "--" is not
# supported, but pigz 2.3.1 supports it. Must be an older version.


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q codecov

# command to run tests
script:
  - make localbuild
  - COVERAGE="coverage run"
  - $COVERAGE python -m pytest -v tests/

after_success:
  - if [ ! -z "$COVERAGE" ]; then codecov; fi

#notifications:
#  email: false
